apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  # #  deployment.kubernetes.io/revision: "1"
  #   kubectl.kubernetes.io/last-applied-configuration: |
  #     {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"chek-echo-app","namespace":"chek-eks-activity"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"echo-app"}},"template":{"metadata":{"labels":{"app":"echo-app"}},"spec":{"containers":[{"args":["-text=Hello, NAME!"],"image":"hashicorp/http-echo","name":"echo-container","ports":[{"containerPort":5678}]}]}}}}
  # creationTimestamp: "2025-03-01T03:21:28Z"
  # generation: 1
  name: chek-echo-app
  namespace: chek-eks-activity
# resourceVersion: "31924"
# uid: 460386a4-78c2-4f7b-a6e3-d027b33cc661
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: echo-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: echo-app
    spec:
      containers:
      - args:
        - -text=Hello, chek!
        image: hashicorp/http-echo
        imagePullPolicy: Always
        name: echo-container
        ports:
        - containerPort: 5678
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
