name: Destroy All AWS Resources

on:
  workflow_dispatch:
    inputs:
      confirm_destroy_all:
        description: 'Type "DESTROY_ALL" to confirm destruction of all resources'
        required: true

jobs:
  destroy_all:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.confirm_destroy_all == 'DESTROY_ALL' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform
        run: terraform init

      - name: List Terraform Workspaces
        run: terraform workspace list

      - name: Destroy All Resources in Each Workspace
        run: |
          for env in dev uat prod; do
            echo "🔹 Switching to workspace: $env"
            terraform workspace select $env || terraform workspace new $env
            terraform destroy -auto-approve | tee terraform-destroy-$env.log
          done

      - name: Delete Terraform Workspaces
        run: |
          for env in dev uat prod; do
            terraform workspace select default
            terraform workspace delete $env || echo "Workspace $env already deleted."
          done

      - name: Cleanup Confirmation
        run: echo "✅ All AWS resources across all environments have been destroyed."
